source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'mongoid', '~> 6.0.0'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'

gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'slim', '~> 3.0', '>= 3.0.7'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.7'
gem 'simple_form', '~> 3.3', '>= 3.3.1'
gem 'factory_girl'
gem 'momentjs-rails'
gem 'bootstrap3-datetimepicker-rails'
gem 'bootstrap-select-rails'

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  gem 'shoulda'
  gem 'factory_girl_rails'
  gem 'dotenv-rails'
  gem 'pry-rails'
  gem 'rails-controller-testing'
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'letter_opener'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'devise'
gem 'jwt'
gem 'html2slim', '~> 0.2.0'
gem 'devise-bootstrapped', '~> 0.1.1'
gem 'font-awesome-sass'
gem 'owlcarousel-rails'
gem 'rack-cors', :require => 'rack/cors'
gem 'rack-attack'
gem 'parsley-rails'
gem 'redis'
gem 'socket.io-rails'
gem 'jquery-datatables-rails', '~> 3.4.0'
gem 'axlsx', '~> 2.0', '>= 2.0.1'
gem 'axlsx_rails', '~> 0.5.0'
gem 'carrierwave', '>= 1.0.0.rc', '< 2.0'
gem 'carrierwave-mongoid', :require => 'carrierwave/mongoid'
gem 'remotipart', '~> 1.2'
gem 'httparty', '~> 0.14.0'
gem 'kaminari'
gem 'gcm'
