default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: green_farm_development

test:
  <<: *default
  database: green_farm_test

production:
  <<: *default
  database: green_farm_production
