development:
  clients:
    default:
      database: green_farm_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false
    use_activesupport_time_zone: true
test:
  clients:
    default:
      database: green_farm_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
  options:
    raise_not_found_error: false
    use_activesupport_time_zone: true
